config/routes.rb
Fq::Application.routes.draw do

  post 'reporter/view', as: :reporter_view

  resources :news

  match 'home' => 'home#index'

  resources :masut_assays

  resources :coil_assays

  resources :gaz_assays

  controller :users do
    match 'users/home' => 'users#home'
    post 'login' => :login
    delete 'logout' => :logout
  end

  resources :users

  root to: 'home#index'

end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :description, :dttm, :title
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  def index
    @news = News.all
    @authorized_user = User.find(session[:user_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])
    @authorized_user = User.find(session[:user_id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = News.new
    @authorized_user = User.find(session[:user_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
    @authorized_user = User.find(session[:user_id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(params[:news])

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Дата время' %><br />
    <%= f.datetime_select :dttm %>
  </div>
  <div class="field">
    <%= f.label 'Заголовок' %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label 'Описание' %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit 'Применить' %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Редактировать новостную запись</h1>

<%= render 'form' %>

<%= link_to 'Смотреть', @news %> |
<%= link_to 'К списку новостей', news_index_path %>

app/views/news/index.html.erb
<h1>Список новостей</h1>

<table>
  <tr>
    <th>Дата время</th>
    <th>Заголовок</th>
    <th>Описание</th>
    <th></th>
  </tr>

<% @news.each do |news| %>
  <tr>
    <td><%= news.dttm.localtime.strftime('%d.%m.%Y %H:%M') %></td>
    <td><%= news.title %></td>
    <td><div id="description"><%== news.description %></div></td>
    <td>
      <%= link_to image_tag("okular.png",:size => "16x16", :alt => "Смотреть",:title => "Смотреть"), news %>
      <%= link_to image_tag("edit_wb.png",:size => "16x16", :alt => "Править", :title => "Править"), edit_news_path(news) %>
      <%= link_to image_tag("delete_wb.png",:size => "16x16", :alt => "Удалить", :title =>"Удалить"), news, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Создать новую новостную запись', new_news_path %>

app/views/news/new.html.erb
<h1>Создать новостную запись</h1>

<%= render 'form' %>

<%= link_to 'К списку новостей', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Дата время:</b>
  <%= @news.dttm %>
</p>

<p>
  <b>Заголовок:</b>
  <%= @news.title %>
</p>

<p>
  <b>Описание:</b>
  <%== @news.description %>
</p>


<%= link_to 'Править', edit_news_path(@news) %> |
<%= link_to 'К списку новостей', news_index_path %>