config/routes.rb
Fq::Application.routes.draw do

  post 'reporter/view', as: :reporter_view

  resources :news

  match 'home' => 'home#index'

  resources :masut_assays

  resources :coil_assays

  resources :gaz_assays

  controller :users do
    match 'users/home' => 'users#home'
    post 'login' => :login
    delete 'logout' => :logout
  end

  resources :users

  root to: 'home#index'

end

app/models/gaz_assay.rb
#encoding: utf-8
class GazAssay < ActiveRecord::Base
  validates_presence_of :dttm, :subdivision, :protocol_num, :ncv
  attr_accessible :dttm, :ncv, :subdivision, :protocol_num, :is_suplier_assay

  scope :public_data, -> {where :is_public_info => true}

  def self.za_period(period_rus)
    case period_rus
      when 'За последний месяц'
        where(dttm: Date.today.months_ago(1) .. Date.tomorrow).order('subdivision','dttm', 'protocol_num')
      when 'Текущий месяц'
        where(dttm: Date.today.at_beginning_of_month .. Date.tomorrow).order('subdivision','dttm', 'protocol_num')
      when 'Прошлый месяц'
        where(dttm: Date.today.months_ago(1).at_beginning_of_month .. Date.today.at_beginning_of_month).order('subdivision','dttm', 'protocol_num')
      when 'Текущий квартал'
        where(dttm: Date.today.at_beginning_of_quarter .. Date.tomorrow).order('subdivision','dttm', 'protocol_num')
      when 'Текущий год'
        where(dttm: Date.today.at_beginning_of_year .. Date.tomorrow).order('subdivision','dttm', 'protocol_num')
      else
        where(dttm: Date.today .. Time.now).order('subdivision','dttm', 'protocol_num')
    end
  end

  def self.filter_sp(sp_name_rus)
    case sp_name_rus
      when 'ТЭЦ-2','ТЭЦ-3','ТЭЦ-4','ТЭЦ-5','КРК'
        where(subdivision: sp_name_rus)
      else
        all
    end
  end
end

app/controllers/gaz_assays_controller.rb
#encoding: utf-8
class GazAssaysController < ApplicationController
  # GET /gaz_assays
  # GET /gaz_assays.json
  def index
    @authorized_user = User.find(session[:user_id])
    @page_title = 'Перечень анализов качества газа'
    case @authorized_user.subdivision
      when 'ТЭЦ-2','ТЭЦ-3','ТЭЦ-4','КРК'
        @gaz_assays = GazAssay.order(:dttm).find_all_by_subdivision(@authorized_user.subdivision)
      else
        @gaz_assays = GazAssay.order(:dttm).all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gaz_assays }
    end
  end

  # GET /gaz_assays/1
  # GET /gaz_assays/1.json
  def show
    @gaz_assay = GazAssay.find(params[:id])
    @authorized_user = User.find(session[:user_id])
    respond_to do |format|
      format.html {render layout: false}
      format.json { render json: @gaz_assay }
    end
  end

  # GET /gaz_assays/new
  # GET /gaz_assays/new.json
  def new
    @page_title = 'Ввод данных качества газа'
    @gaz_assay = GazAssay.new
    @authorized_user = User.find(session[:user_id])
    @gaz_assay.subdivision = @authorized_user.subdivision
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gaz_assay }
    end
  end

  # GET /gaz_assays/1/edit
  def edit
    @page_title = 'Редактирование данных качества газа'
    @gaz_assay = GazAssay.find(params[:id])
    @authorized_user = User.find(session[:user_id])
  end

  # POST /gaz_assays
  # POST /gaz_assays.json
  def create
    @gaz_assay = GazAssay.new(params[:gaz_assay])
    @authorized_user = User.find(session[:user_id])
    respond_to do |format|
      if @gaz_assay.save
        format.html { redirect_to gaz_assays_url, notice: 'Данные нового анализа газа успешно записаны.' }
        format.json { render json: @gaz_assay, status: :created, location: @gaz_assay }
      else
        format.html { render action: "new" }
        format.json { render json: @gaz_assay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gaz_assays/1
  # PUT /gaz_assays/1.json
  def update
    @gaz_assay = GazAssay.find(params[:id])
    @authorized_user = User.find(session[:user_id])
    respond_to do |format|
      if @gaz_assay.update_attributes(params[:gaz_assay])
        format.html { redirect_to gaz_assays_url, notice: 'Данные качественного анализа газа успешно скорректированы.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gaz_assay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gaz_assays/1
  # DELETE /gaz_assays/1.json
  def destroy
    @gaz_assay = GazAssay.find(params[:id])
    @gaz_assay.destroy

    respond_to do |format|
      format.html { redirect_to gaz_assays_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/gaz_assays_helper.rb
module GazAssaysHelper
end

app/views/gaz_assays/_form.html.erb
<%= form_for(@gaz_assay) do |f| %>
  <% if @gaz_assay.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gaz_assay.errors.count, "error") %> prohibited this gaz_assay from being saved:</h2>

      <ul>
      <% @gaz_assay.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <fieldset class="gaz_assays_data">

      <div class="field">
        <%= f.label 'СП:' %>
        <%= f.select :subdivision, ['ТЭЦ-2','ТЭЦ-3','ТЭЦ-4','КРК'] %>
      </div>
      <div class="field">
        <%= f.label 'Данные поставщика?:' %>
        <%= f.check_box :is_suplier_assay %>
      </div>
      <div class="field">
        <%= f.label 'Протокол/паспорт №:' %>
        <%= f.text_field :protocol_num, size: 8 %>
      </div>
      <div class="field">
        <%= f.label 'Дата:' %>
        <%= f.date_select :dttm, use_month_numbers: true, order: [:day, :month, :year], default: Date.today %>
      </div>
      <div class="field">
        <%= f.label 'Низшая теплота сгорания (ккал/кг):' %>
        <%= f.text_field :ncv, size: 8 %>
      </div>
      <div class="actions">
        <%= f.submit 'Принять' %>
      </div>
    </fieldset>


<% end %>

app/views/gaz_assays/_ga_data_table.html.erb
<p>
  <b>СП</b>
  <%= @gaz_assay.subdivision %>
</p>
<div class="form_title">
  <h2>
    <b>Протокол анализа газа № </b>
    <%= @gaz_assay.protocol_num %>
  </h2>
</div>


<p>
  <b>Дата отбора пробы: </b>
  <%= @gaz_assay.dttm.strftime("%d.%m.%Y") %>
</p>

<table>
  <tr>
    <th>№</th>
    <th>Наименование показателя</th>
    <th>Обознач.</th>
    <th>Ед. изм.</th>
    <th>Результат</th>
  </tr>
  <tr>
    <td>1</td>
    <td class="align_left">Низшая теплота сгорания</td>
    <td>Q<sub>i</sub></td>
    <td>ккал/кг</td>
    <td><%= @gaz_assay.ncv %></td>
  </tr>
</table></br>
<div class="no_print">
  <%= link_to 'К данным по газу', gaz_assays_path %> |
  <%= link_to 'Править', edit_gaz_assay_path(@gaz_assay) %> |
  <%= link_to_function 'Печать', 'window.print();',class: 'nav_link' %>
</div>
<div class="no_view">
  <table class="sign">
    <tr><td colspan="2"></td> </tr>
    <tr>
      <td align="left">Начальник химического цеха</td>
      <td>_______________________________________________________</td>
    </tr>
    <tr>
      <td align="left">Анализ проводил</td>
      <td>_______________________________________________________</td>
    </tr>
  </table>
</div>

app/views/gaz_assays/_ga_supp_data_table.html.erb
<p>
  <b>СП</b>
  <%= @gaz_assay.subdivision %>
</p>
<div class="form_title">
  <h2>
    <b>Паспорт качества газа № </b>
    <%= @gaz_assay.protocol_num %>
  </h2>
</div>


<p>
  <b>Месяц действия: </b>
  <%= @gaz_assay.dttm.strftime("%m.%Y") %>
</p>

<table>
  <tr>
    <th>№</th>
    <th>Наименование показателя</th>
    <th>Обознач.</th>
    <th>Ед. изм.</th>
    <th>Результат</th>
  </tr>
  <tr>
    <td>1</td>
    <td class="align_left">Низшая теплота сгорания</td>
    <td>Q<sub>i</sub></td>
    <td>ккал/кг</td>
    <td><%= @gaz_assay.ncv %></td>
  </tr>
</table></br>
<div class="no_print">
  <%= link_to 'К данным по газу', gaz_assays_path %> |
  <%= link_to 'Править', edit_gaz_assay_path(@gaz_assay) %> |
  <%= link_to_function 'Печать', 'window.print();',class: 'nav_link' %>
</div>

app/views/gaz_assays/edit.html.erb
<%= render 'form' %>

<br/>
<%= link_to 'К перечню анализов газа', gaz_assays_path %>
<% content_for :manual do %>
    <p id="manual">
      <i>Краткая справка:</i><br/>
      На этой странице Вы получаете возможность редактировать данные о калорийности газа.<br />
      Некоторые поля обязательны для заполнения. Если они не будут заполнены, при сохранении поле будет выделено, и Вы получите предупреждение.<br />
      Разделитель целой и дробной части - точка.<br/>
      Данные изменяет только кнопка "Принять". Если Вы не хотите вносить изменения в базу данных, можно нажать на любую ссылку. <br />
      <br />
      Для завершения работы в приложении всегда можно нажать кнопку 'Выход' в верхнем правом углу.
    </p>
<% end %>

app/views/gaz_assays/index.html.erb
<table>
  <tr>
    <th>Структурное<br/>подразделение</th>
    <th>Дата</th>
    <th>Номер<br/>протокола/паспорта</th>
    <th>Низшая теплота<br/>сгорания (ккал/кг)</th>
    <th></th>
  </tr>

<% @gaz_assays.each do |gaz_assay| %>
  <tr <%= 'id=suplier_data' if gaz_assay.is_suplier_assay %>>
    <td><%= gaz_assay.subdivision %></td>
    <td><%= gaz_assay.dttm.strftime("%d.%m.%Y") %></td>
    <td><%= gaz_assay.protocol_num %></td>
    <td><%= gaz_assay.ncv %></td>
    <td>
      <%= link_to image_tag("show_wb.png",:size => "16x16", :alt => "Подробно", :title => "Подробно"), gaz_assay if grant_for_action(false,@authorized_user)[:can_edit]%>
      <%= link_to image_tag("edit_wb.png",:size => "16x16", :alt => "Править", :title => "Править"), edit_gaz_assay_path(gaz_assay) if grant_for_action(false)[:can_edit]%>
      <%= link_to image_tag("delete_wb.png",:size => "16x16", :alt => "Удалить", :title =>"Удалить"), gaz_assay, method: :delete, data: { confirm: 'Вы уверены?' } if grant_for_action(false)[:can_delete]%>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Ввести данные новой пробы', new_gaz_assay_path  if grant_for_new_assay? %>

<% content_for :manual do %>
    <p id="manual">
      <i>Краткая справка:</i><br/>
      На этой странице Вы получаете возможность просматривать данные о качестве газа. Строки выделенные цветом соответствуют данным сертификатов.
      Здесь доступны следующие действия:<br />
      <%= image_tag("show_wb.png") %> - посмотреть данные подробнее и получить возможность вывести форму на печать;<br />
      <%= image_tag("edit_wb.png") %> - редактировать данные анализов качества;<br />
      <%= image_tag("delete_wb.png") %> - удалить данные анализов качества.<br />
      <br />
      Для завершения работы в приложении всегда можно нажать кнопку 'Выход' в верхнем правом углу.
    </p>
<% end %>

app/views/gaz_assays/new.html.erb
<%= render 'form' %>

<br />
<%= link_to 'К перечню проб газа', gaz_assays_path %>
<% content_for :manual do %>
    <p id="manual">
      <i>Краткая справка:</i><br/>
      На этой странице Вы получаете возможность ввести данные о калорийности газа.<br />
      Некоторые поля обязательны для заполнения. Если они не будут заполнены, при сохранении поле будет выделено, и Вы получите предупреждение.<br />
      Разделитель целой и дробной части - точка.<br/>
      Данные изменяет только кнопка "Принять". Если Вы не хотите вносить изменения в базу данных, можно нажать на любую ссылку. <br />
      <br />
      Для завершения работы в приложении всегда можно нажать кнопку 'Выход' в верхнем правом углу.
    </p>
<% end %>

app/views/gaz_assays/show.html.erb
<html>
<head>
  <title>Качество топлива. Подробно.</title>
  <%= stylesheet_link_tag "for_print", media: 'print' %>
  <%= stylesheet_link_tag "for_print" %>
  <style type="text/css" media="print">
      div.no_print {display: none;}
  </style>
  <style type="text/css" media="screen">
      div.no_view {display: none;}
  </style>

</head>
<body class="paper">
<%= @gaz_assay.is_suplier_assay ? render('ga_supp_data_table') : render('ga_data_table') %>
</body>


</html>